[project]
name = "gpt-oss-hackathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.99.9",
    "python-dotenv>=1.1.1",
    "typing-extensions>=4.7",
]
